name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      RABBITMQ_DSN: "amqp://guest:guest@127.0.0.1:5672/"
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: black --check .
      - run: isort --check .
      - run: mypy .
      - run: ruff .
      - run: pytest --verbose --cov message_lib --cov-report term-missing

  release:
    if: github.event_name == 'push'
    name: release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
      - run: poetry config repositories.azure https://pkgs.dev.azure.com/binkhq/_packaging/binkhq/pypi/upload/
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry build
      - run: poetry publish -r azure
